name: Deploy to Cloud Run | Development

on:
  push:
    branches: [development]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: gcp-express-supabase-dev
  REGION: asia-southeast1
  PORT: 8080

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Authorize Docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build \
          --build-arg PORT="${{ env.PORT }}" \
          --build-arg DATABASE_URL="${{ secrets.DATABASE_URL_DEV }}" \
          --build-arg SUPABASE_URL="${{ secrets.SUPABASE_URL_DEV }}" \
          --build-arg SUPABASE_KEY="${{ secrets.SUPABASE_KEY_DEV }}" \
          --build-arg SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY_DEV }}" \
          -t asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} -f Dockerfile.development .
          docker push asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
          --port ${{env.PORT}} \
          --region ${{ env.REGION }} \
          --image asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} \
          --platform "managed" \
          --allow-unauthenticated \
          --quiet
